### ISSUE TITLE
Error on setup: Error Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by wormiedk** [scaarup/aula#100]
**Describe the bug or problem (In Danish is OK)**
Ved opsætning af integration fåes: Error
Config flow could not be loaded: {"message":"Invalid handler specified"}
Jeg har haft den til at virke men slettede den for at prøve at geninstallere da den holdt op med at virke

**Please answer the following**
- Version of integration: 0.1.32
- Version of Home Assistant: 2023.5.b04
- [ ] I have more than one child
- [ ] My children are attending different schools / institutions

**Please provide debug log from the integration**
Kan ikke installere :)

**Comment by scaarup** [comment]
Du kan stadig hive debug log ud, selvom config flowet fejler.

**Comment by wormiedk** [comment]
Super. Så kommer fejl i log her:

```
Logger: homeassistant.config_entries
Source: config_entries.py:863
First occurred: 10:01:42 (1 occurrences)
Last logged: 10:01:42

Error occurred loading flow for integration aula: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)
```

**Comment by scaarup** [comment]
Jeg kan ikke se nogen debug linjer. Du skal lige have debug slået til på integrationen, restart HA og prøv at add den igen.

Du oplyser dog, at du kører en beta version af HA. Det første jeg vil foreslå dig, er selvfølgelig at forsøge med en stable version først.

**Comment by bogolob** [comment]
The async_get_registry call has been deprecated 2 years ago and was removed in 2023.5:

![image](https://user-images.githubusercontent.com/79573606/235761024-cad25d8f-5dee-4e50-962b-293b683a8565.png)

The Aula plugin just needs a trivial replacement of async_get_registry to async_get, since that is all that the old function did anyway:

![image](https://user-images.githubusercontent.com/79573606/235761653-41053a85-fe16-4496-95f6-f0e11e128dda.png)

**Comment by scaarup** [comment]
Thanks @bogolob 

Very good info 👍

Will publish a fix soon.

**Comment by scaarup** [comment]
@wormiedk vil du teste v0.1.33? Er ude som pre-release/beta nu.

**Comment by bogolob** [comment]
I upgraded my Homeassistant and Aula plugins to 2023.5b05 and 0.1.33 and the integration works.

**Comment by scaarup** [comment]
> I upgraded my Homeassistant and Aula plugins to 2023.5b05 and 0.1.33 and the integration works.

Awesome 👌🏻. Did you also test the config flow?

**Comment by wormiedk** [comment]
Config flow virker nu også :)

**Comment by scaarup** [comment]
Tak begge :)
Så lukker vi denne.
