### ISSUE TITLE
Ide/Sparring: Add Huskelisten-topics to Google Tasks

### ISSUE THREAD

**Issue by sorentorp** [scaarup/aula#102]
**Describe the bug or problem (In Danish is OK)**

**Please answer the following**
- Version of integration: Current
- Version of Home Assistant: Current
- [ YES] I have more than one child
- [NO] My children are attending different schools / institutions

**Comment by scaarup** [comment]
Hej @sorentorp .
Jeg skal lige bruge noget mere info her :). Hvad går det ud på og hvorfor har du sat en "bug" label på?

**Comment by sorentorp** [comment]
Det er ikke en bug - kan jeg oprette det uden? Det er mere en sparring/feature req :-) 

Jeg vil gerne bruge de data jeg får fra Systematics Huskeliste, til andre automatiseringer i HA. Er det muligt?

**Comment by sorentorp** [comment]
flytter til discussion...
