### ISSUE TITLE
Kort frist til Unilogin-passwordudløb giver Access to Aula API was denied

### ISSUE THREAD

**Issue by Jogge** [scaarup/aula#105]
Jeg får følgende fejl i min Aula integration: `Access to Aula API was denied. Please check that you have entered the correct credentials.`

Jeg forsøgte at logge ind på aula med Unilogin, og fik at vide at mit password snart udløb og blev bedt om at ændre passwordet.

Jeg ved at at det er en kendt fejl at man skal geninstallerer Aula, når ens password ændres. Denne fejl sker dog før mit password er blevet ændret eller udløbet.

- Version of integration: v0.1.33
- Version of Home Assistant: Home Assistant 2023.5.2
- ✅ I have more than one child
- ✅ My children are attending different schools / institutions

![billede](https://github.com/scaarup/aula/assets/15981279/f84688b0-a6ac-4aec-a6db-1db65064e297)
```
This error originated from a custom integration.

Logger: custom_components.aula.client
Source: custom_components/aula/client.py:149
Integration: Aula (documentation, issues)
First occurred: 08:54:32 (4 occurrences)
Last logged: 09:16:23

Access to Aula API was denied. Please check that you have entered the correct credentials.
```

![billede](https://github.com/scaarup/aula/assets/15981279/dafb102e-05a2-4fcb-b5c7-3fddb287a6c6)

**Comment by Jogge** [comment]
Efter ændring af password og geninstallation af Aula integrationen, kører det igen.

**Comment by scaarup** [comment]
Tak @Jogge 
Den bliver lidt svær at teste. Men jeg må prøve at huske det til næste gang mit passwd er ved at udløbe :)
