### ISSUE TITLE
Satus 7 

### ISSUE THREAD

**Issue by ghozt1989** [scaarup/aula#107]
Hej jeg har denne status (7) når knægten tjekker ind i hallen når han er SFO kan jeg selv fixe det et sted eller kan jeg måske få dig til det hvis det altså er noget der lige er til at fixe :) 

Sig til hvis du mangler nogle info og hvordan jeg evt finder disse info :)

![image](https://github.com/scaarup/aula/assets/7705364/078915af-41c1-4de7-9435-5db91f18c424)

**Comment by scaarup** [comment]
Hej.
Hvad står der mon som tekst for status 7 i Aula appen?

**Comment by ghozt1989** [comment]
Kan jeg lige se senere når de går i hallen igen hvis de gør det i dag :)

Men på skærmet(aula pcen) i sfoén skal de trykke på HALLEN når den går i status 7

**Comment by scaarup** [comment]
Hm "Hallen", lyder lidt som noget custom per institution måske.

**Comment by ghozt1989** [comment]
![IMG_9535](https://github.com/scaarup/aula/assets/7705364/907ed1f2-bf94-466d-a9d0-d3002369a877)
Jeg fangede her et billede af hvordan det ser ud på aula når de trykker de er i "hallen"

**Comment by scaarup** [comment]
Okay det ser fint ud. Problemet er lidt, at jeg ikke ved om status=7 betyder "Hallen" for alle institutioner i hele Aula.

**Comment by ghozt1989** [comment]
Ah okay :) er der måske evt noget jeg kan gøre hos mig selv så?

**Comment by scaarup** [comment]
Prøv at se "7.3.1 Fysiske placeringer"
https://aulainfo.dk/wp-content/uploads/Administratorvejledning-R0.9.pdf

Der er nok ikke nogen vej uden om en template sensor.

**Comment by ghozt1989** [comment]
Tak må se om jeg kan finde ud af det :)

**Comment by ghozt1989** [comment]
Jeg har prøvet at ændre i koden i fil sensor.py linje 107 og 111. Ved ikke om det hjælper mig selvføldig skal jeg huske at ændre det igen ved evt update

**Comment by scaarup** [comment]
Linje 110 burde være nok :)
