### ISSUE TITLE
Hvordan laver du authentication?

### ISSUE THREAD

**Issue by sptv2reg** [scaarup/aula#108]
Fedt initiativ - Men hvordan logger du egentlig programmatisk ind på aula. Kan se der er noget brugernavn/password, men er MitID ikke et krav?

**Comment by sptv2reg** [comment]
Svarer lige mig selv - man kan tilsyneladende oprette brugernavn/password som alternativ. Det vidste jeg ikke.

**Comment by scaarup** [comment]
> Svarer lige mig selv - man kan tilsyneladende oprette brugernavn/password som alternativ. Det vidste jeg ikke.

Yes med Unilogin 🙂. 
Der er planer om at Unilogin kun skal være til elever og forældre skal bruge MitID. Ved ikke lige hvornår dog.
