### ISSUE TITLE
Calendar update fails with "no matching widgets"

### ISSUE THREAD

**Issue by VaabenDK** [scaarup/aula#111]
**After installing and connection to Aula, then the integration does not retrieve the calendar**

- Version of integration: 0.1.33
- Version of Home Assistant: 2023.08.03
- [ ] I have more than one child: No
- [ ] My children are attending different schools / institutions: No

[debug aula.txt](https://github.com/scaarup/aula/files/12448197/debug.aula.txt)
[skoleskema.json.txt](https://github.com/scaarup/aula/files/12448200/skoleskema.json.txt)

**Comment by scaarup** [comment]
Is it correct, that you have never seen this message in your logs?
_LOGGER.debug("Parsing skoleskema.json...")
It looks strange ... Could you try to set up the integration from scratch without enabling "ugeplaner"? Just to see if that has an effect on the missing calendar.

**Comment by scaarup** [comment]
Also leave the integration running for at least 10 minutes, since that is the time between calendar updated

**Comment by VaabenDK** [comment]
Hi there. Sorry for giving feedback so late. I finally had time to do a proper logfile 

[2023-09-07 185024.111.txt](https://github.com/scaarup/aula/files/12566105/2023-09-07.185024.111.txt)

While being patient, I now get the calendar (Skoleskema) in - but not "Ugeplaner". My sons school uses Meebook - but maybe the kind of widget is not supported?

Widgets found: {'0013': 'Nyttige links', '0047': 'Fravær - forældreindberetning', '0119': 'Meebook overblik'}
You have enabled ugeplaner, but we cannot find any matching widgets (0029,0004) in Aula.

This is the only meebook widget I can see when logging into Aula - no Ugeplaner Widget - so maybe the pull of Ugeplaner is not possible?
![2023-09-09 17_17_01-AULA Meebook](https://github.com/scaarup/aula/assets/58402038/276931a4-aa68-4340-b5de-9d7cf1fbd3e5)
