### ISSUE TITLE
Request: Adding ugeplan entries as calendar events

### ISSUE THREAD

**Issue by AThomsen** [scaarup/aula#112]
Jeg vil gerne lave en automation, så der hver eftermiddag sker en TTS-notifikation om hvad der er på ugeplanen til i morgen. Heri skriver læreren nemlig hvilke lektier der skal laves til dagen.

Jeg kan selvfølgelig pille `ugeplan` og `ugeplan_next` (hvis det er weekend) fra hinanden, men det vil være noget nemmere hvis de bare indlæses som calendar events og så hentes i en automation med `.list_events`.

**Please answer the following**
- Version of integration: latest
- Version of Home Assistant:  latest
- [x] I have more than one child
- [x] My children are attending different schools / institutions

**Comment by AThomsen** [comment]
closed as not a bug...

**Comment by scaarup** [comment]
Der er stor forskel på hvordan de forskellige skoler bruger ugeplaner/ugenoter. Det er ren fritekst og nogle opdeler i fag, andre i dage osv. 
Hvis din skole er konsekvent i den måde de skriver ugeplaner, så bør du kunne hive den tekst ud du skal bruge, vha. templating.
