### ISSUE TITLE
Request: Adding ugeplan entries as calendar events

### ISSUE THREAD

**Issue by AThomsen** [scaarup/aula#113]
Jeg vil gerne lave en automation, så der hver eftermiddag sker en TTS-notifikation om hvad der er på ugeplanen til i morgen. Heri skriver læreren nemlig hvilke lektier der skal laves til dagen.

Jeg kan selvfølgelig pille `ugeplan` og `ugeplan_next` (hvis det er weekend) fra hinanden, men det vil være noget nemmere hvis de bare indlæses som calendar events og så hentes i en automation med `.list_events`.

**Comment by scaarup** [comment]
Der er stor forskel på hvordan de forskellige skoler bruger ugeplaner/ugenoter. Det er ren fritekst og nogle opdeler i fag, andre i dage osv.
Hvis din skole er konsekvent i den måde de skriver ugeplaner, så bør du kunne hive den tekst ud du skal bruge, vha. templating.
Det betyder, at det ikke er muligt for mig, at "konvertere" ugeplaner til kalender events - det er som sagt blot fritekst.

**Comment by AThomsen** [comment]
Det er denne struktur jeg taler om, som ikke er fritekst: https://github.com/scaarup/aula/blob/86d14000cb2a50670768207cfb428fb9cf58c2d1/custom_components/aula/client.py#L363C41-L363C41

**Comment by scaarup** [comment]
Aha fra Meebook.
Vil du lige prøve at smide denne ind:
`_LOGGER.debug(ugeplan)`
før linje 363 i client.py

**Comment by AThomsen** [comment]
Forsøg på fix i #119
