### ISSUE TITLE
No entries are provided by the plugin anymore

### ISSUE THREAD

**Issue by ricobach** [scaarup/aula#114]
**Describe the bug or problem (In Danish is OK)**
No entries are provided by the plugin anymore, in the log i can see all children and the school and institutions..   
--> im not sure if its related to the change og aula API from v15 to v16

**Please answer the following**
- Version of integration: v0.1.33
- Version of Home Assistant: 2023.8.4
- [ x] I have more than one child
- [ x] My children are attending different schools / institutions

**Please provide debug log from the integration**
- Enable by adding the following to your configuration.yaml:
```
logger:
  default: info
  logs:
    custom_components.aula: debug
```
- Restart Home Assistant
- Capture all log lines (from the integration only), save it to a file and attach it to here.
- 
[aulalog.txt](https://github.com/scaarup/aula/files/12497118/aulalog.txt)

**Comment by scaarup** [comment]
Prøv lige at hop ind på Aula på din telefon/web og se om du har ulæste beskeder. Marker dem som læst og genstart din HA og se om samme fejl opstår.

**Comment by ricobach** [comment]
Jeg har som regel  flere ulæste beskeder da der er meget "spam", men der var komme en som var markeret som "følsom information" da jeg læste den virkede det  igen..  

Tusinde tak :D

**Comment by ricobach** [comment]
Ligeså snart at jeg markere den som ulæst. kom fejlen tilbage...   jeg nåede ikke at fange loggen og når jeg prover lige nu er Aula ikke tilgængelig..    jeg prøver når aula er oppe igen..

**Comment by ricobach** [comment]
Når den første/nyeste besked som er ulæst er "følsom information" kommer fejlen(se log). hvis jeg markere en besked før som ulæst eller markere den følsomme besked som læst, virker alt som normalt..   

[aulalog3.txt](https://github.com/scaarup/aula/files/12505687/aulalog3.txt)

**Comment by scaarup** [comment]
Men fik du indkommenteret den linje jeg nævnte?

**Comment by ricobach** [comment]
Ja, den er indkommenteret, og når den ikke tager fat i den følsomme besked kommer der også en masse ekstra log..   jeg har lige lagt mærke til at hvis jeg logger ind på aula fra en browser med unilogin kræver den MitID login..  

<img width="492" alt="Screenshot 2023-09-03 at 20 14 26" src="https://github.com/scaarup/aula/assets/40454890/0627aed7-5438-49bd-8aaf-cdc8636efc49">

<img width="1111" alt="Screenshot 2023-09-03 at 20 17 41" src="https://github.com/scaarup/aula/assets/40454890/6a91103e-d94c-4b5d-917a-05d83236d91c">

**Comment by scaarup** [comment]
Fedt, det var bare mig, der overså det.

Det her leder vi efter:
`2023-09-03 12:03:44.889 DEBUG (SyncWorker_11) [custom_components.aula.client] threadres {"status":{"code":403,"subCode":8,"errorInformation":[],"message":""},"data":null,"trace":"n\/a"}`

Så jeg mangler at håndtere den i integrationen. Tak :)

**Comment by scaarup** [comment]
@ricobach det kan være du vil teste den beta/pre-release, jeg lige har lagt ud? Selvfølgelig gerne med følsom besked som ulæst.

**Comment by ricobach** [comment]
Jeg har testet med følsom besked som ulæst og det virker som jeg ville forvente..

**Comment by scaarup** [comment]
Okay tak. Så betragter vi det som en løsning.
