### ISSUE TITLE
Kan ikke få det til at virke apiUrl fejl

### ISSUE THREAD

**Issue by KlausLadegaard** [scaarup/aula#116]
Hej, god ide, men kan ikke få det til at virke

Har nu installeret via HACS 4 gange og 1 gang manual 
Får denne fejl 

Logger: homeassistant.components.sensor
Source: custom_components/aula/client.py:143
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 21.56.53 (1 occurrences)
Last logged: 21.56.53

Error while setting up aula platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/aula/sensor.py", line 58, in async_setup_entry
    await hass.async_add_executor_job(client.update_data)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aula/client.py", line 143, in update_data
    response = self._session.get(self.apiurl + "?method=profiles.getProfilesByLogin", verify=True).json()
                                 ^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'apiurl'

Login er valid

Jeg kører
Home Assistant 2023.8.4 i docker
Python 3.11.4

Nogen ide til hvad jeg kan gøre?

**Comment by scaarup** [comment]
Hvilken version af integrationen kører du? Og der skal noget debug log til.

**Comment by KlausLadegaard** [comment]
Hej Søren, kører Git close af den nyeste.. 0.1.34Og debug log er sat via gui, men hvor gemmes debug data, har sendt alt jeg kan i gui..Sendt fra Outlook til Android

**Comment by scaarup** [comment]
Jeg tror ikke det virker at sætte debug log via gui. 
Og den version du kører er en pre-release. Hop venligst tilbage til seneste stable.

**Comment by KlausLadegaard** [comment]
Jeg har nu hentet 0.1.33 som Zip, og pakket den ud i custom_component folderen
samme fejl desværre

hvis det ikke er måden at aktivere debug
kan du så enten dele guide eller sige hvordan? samt hilken fil det lander i? kan ikke finde noget om dette

**Comment by scaarup** [comment]
```
logger:
  default: info
  logs:
    custom_components.aula: debug
```

Står på den bug report template du gerne skulle få præsenteret når du laver et issue her.

**Comment by KlausLadegaard** [comment]
Undskyld mange gange, havde af ren vane fra andet sags system på job slettet den text da den ikke gav mening lige da jeg oprettede sagen

- Version of integration: Aula integration, version: 0.1.33
- Hacs version: 1.32.1
- Version of Home Assistant:  Home Assistant 2023.8.4 Brugerflade 20230802.1 - latest 
- [No] I have more than one child
- [No] My children are attending different schools / institutions

Jeg har samlet input i loggen nu
[home-assistant_2023-09-06T17-22-54.634Z.log](https://github.com/scaarup/aula/files/12540776/home-assistant_2023-09-06T17-22-54.634Z.log)

**Comment by scaarup** [comment]
Er din log fra når Home Assistant starter eller når du har konfigureret integrationen i UI'et?

**Comment by KlausLadegaard** [comment]
Hej 

Jeg fjernede aula under enheder / integrationer
Jeg fjernede AULA fra custom_components
Genstarter HA
Henter Aula zip og udpakker under custom_components
Genstarter HA
Konfigurere i UI
Genstart HA
-> tager loggen

**Comment by scaarup** [comment]
Okay.
Jeg kan slet ikke se, at du kommer ned i login funktionen og det er meget mærkeligt. Jeg kender ikke rigtig dit setup, men det lader til, at du er lidt alene med det problem og derfor tænker jeg, at vi ikke har at gøre med en bug i integrationen, men nok nærmere noget i dit miljø, der er problemet.

**Comment by KlausLadegaard** [comment]
Hej, efter dit svar har jeg reinstalleret hele miljøet

Jeg kører et vanilla setup via Docker, dvs det er i container
Jeg installer hacs

Og Aula 0.1.33 gennem denne
Tilføjer componenten under indstillinger
Hvorefter en login boks kommer frem, (skema samt ugeplan, kan tilvælges)
Fejlen kommer ved config & genstart

Jeg kan ikke se hvad jeg kan gøre gat

Jeg er nu på Homeassistant 2023.9.1

**Comment by KlausLadegaard** [comment]
Jeg har nu lavet et fuld test miljø ;) og kun installeret docker pod med HomeAssistant
Installeret HACS + Editor til yaml filer
Derefter ser jeg at vi lander i login, men stadig samme fejl - måske min filtering havde fejl
[home-assistant_2023-09-09T18-36-49.144Z.log](https://github.com/scaarup/aula/files/12566465/home-assistant_2023-09-09T18-36-49.144Z.log)

Her ses 
2023-09-09 20:36:54.245 DEBUG (SyncWorker_4) [custom_components.aula.client] is_logged_in? False
2023-09-09 20:36:54.246 DEBUG (SyncWorker_4) [custom_components.aula.client] Logging in
2023-09-09 20:36:56.250 ERROR (MainThread) [custom_components.aula.sensor] Unexpected error fetching sensor data: 'action'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 293, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 248, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

Jeg ved ikke om det kan have noget med at jeg har haft flere på samme skole, største stoppede i sommers :) bare en ide

**Comment by scaarup** [comment]
Okay - det er jo lidt svært. Jeg kan ikke genskabe dit problem og jeg har ikke hørt om andre med samme problem.
Du bliver nok nødt til at smide nogle debug linjer ind i login funktionen, så du kan se hvad der foregår.

**Comment by scaarup** [comment]
Sønnens profiler? Du logger vel ind som dig selv?

**Comment by KlausLadegaard** [comment]
Eneste unilogin vi har, ellers er det MitID..
Giver også mening da det er ugeplan til hans værelse :)

**Comment by KlausLadegaard** [comment]
FUCK, fandt eget login, men har jo ikke brugt det siden de gik til nemid

Nu kommer der noget ind.. 
Det var en fejl 50
