### ISSUE TITLE
ugeplan: Not available

### ISSUE THREAD

**Issue by ronniebach** [scaarup/aula#118]
Jeg får ingen data frem: 
ugeplan: Not available
ugeplan_next: Not available
Når jeg logger ind med mit unilogin (samme som integration er sat op med) kan jeg fint se ugeplaner.

**Please answer the following**
- Version of integration: 0.1.34
- Version of Home Assistant: 2023.9.2
- [x] I have more than one child. 2
- [ ] My children are attending different schools / institutions

**Please provide debug log from the integration**
	Linie  402: 2023-09-30 14:03:16.023 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.aula
	Linie  405: 2023-09-30 14:03:16.026 DEBUG (SyncWorker_0) [custom_components.aula.client] is_logged_in? False
	Linie  406: 2023-09-30 14:03:16.026 DEBUG (SyncWorker_0) [custom_components.aula.client] Logging in
	Linie  473: 2023-09-30 14:03:17.561 DEBUG (SyncWorker_0) [custom_components.aula.client] Trying API at https://www.aula.dk/api/v16
	Linie  474: 2023-09-30 14:03:17.606 WARNING (SyncWorker_0) [custom_components.aula.client] API was expected at https://www.aula.dk/api/v16 but responded with HTTP 410. The integration will automatically try a newer version and everything may work fine.
	Linie  475: 2023-09-30 14:03:17.608 DEBUG (SyncWorker_0) [custom_components.aula.client] Trying API at https://www.aula.dk/api/v17
	Linie  476: 2023-09-30 14:03:17.799 DEBUG (SyncWorker_0) [custom_components.aula.client] Found API on https://www.aula.dk/api/v17
	Linie  477: 2023-09-30 14:03:18.012 DEBUG (SyncWorker_0) [custom_components.aula.client] LOGIN: True
	Linie  478: 2023-09-30 14:03:18.012 DEBUG (SyncWorker_0) [custom_components.aula.client] Config - schoolschedule: False, config - ugeplaner: True
	Linie  479: 2023-09-30 14:03:18.012 DEBUG (SyncWorker_0) [custom_components.aula.client] Child ids and names: {1050096: 'KID_1', 1421410: 'KID_2'}
	Linie  480: 2023-09-30 14:03:18.012 DEBUG (SyncWorker_0) [custom_components.aula.client] Child ids and institution names: {1050096: 'NAMEOF_Skole', 1421410: 'NAMEOF_Skole'}
	Linie  481: 2023-09-30 14:03:18.012 DEBUG (SyncWorker_0) [custom_components.aula.client] Institution codes: ['731003']
	Linie  482: 2023-09-30 14:03:18.092 WARNING (SyncWorker_0) [custom_components.aula.client] Unable to retrieve presence data from Aula from child with id 1050096. Some data will be missing from sensor entities.
	Linie  483: 2023-09-30 14:03:18.170 WARNING (SyncWorker_0) [custom_components.aula.client] Unable to retrieve presence data from Aula from child with id 1421410. Some data will be missing from sensor entities.
	Linie  484: 2023-09-30 14:03:18.171 DEBUG (SyncWorker_0) [custom_components.aula.client] Child ids and presence data status: {'1050096': 0, '1421410': 0}
	Linie  485: 2023-09-30 14:03:19.306 DEBUG (SyncWorker_0) [custom_components.aula.client] Widgets found: {'0047': 'Fravær - forældreindberetning', '0030': 'MinUddannelse - Opgaver', '0029': 'MinUddannelse – Ugenoter', '0028': 'MinUddannelse – Forløb', '0120': 'MinUddannelse - Meddelelsesbog'}
	Linie  486: 2023-09-30 14:03:19.306 DEBUG (SyncWorker_0) [custom_components.aula.client] Requesting token for widget 0029
	Linie  487: 2023-09-30 14:03:19.421 DEBUG (SyncWorker_0) [custom_components.aula.client] Requesting token for widget 0029
	Linie  494: 2023-09-30 14:03:19.570 DEBUG (MainThread) [custom_components.aula.sensor] Finished fetching sensor data in 3.544 seconds (success: True)
	Linie  495: 2023-09-30 14:03:19.691 DEBUG (SyncWorker_5) [custom_components.aula.client] is_logged_in? True
	Linie  496: 2023-09-30 14:03:19.691 DEBUG (SyncWorker_5) [custom_components.aula.client] Child ids and names: {1050096: 'KID_1', 1421410: 'KID_2'}
	Linie  497: 2023-09-30 14:03:19.691 DEBUG (SyncWorker_5) [custom_components.aula.client] Child ids and institution names: {1050096: 'NAMEOF_Skole', 1421410: 'NAMEOF_Skole'}
	Linie  498: 2023-09-30 14:03:19.691 DEBUG (SyncWorker_5) [custom_components.aula.client] Institution codes: ['731003']
	Linie  506: 2023-09-30 14:03:19.754 WARNING (SyncWorker_5) [custom_components.aula.client] Unable to retrieve presence data from Aula from child with id 1050096. Some data will be missing from sensor entities.
	Linie  523: 2023-09-30 14:03:19.831 WARNING (SyncWorker_5) [custom_components.aula.client] Unable to retrieve presence data from Aula from child with id 1421410. Some data will be missing from sensor entities.
	Linie  524: 2023-09-30 14:03:19.834 DEBUG (SyncWorker_5) [custom_components.aula.client] Child ids and presence data status: {'1050096': 0, '1421410': 0}
	Linie  666: 2023-09-30 14:03:20.722 DEBUG (SyncWorker_5) [custom_components.aula.client] Requesting token for widget 0029
	Linie  667: 2023-09-30 14:03:20.863 DEBUG (SyncWorker_5) [custom_components.aula.client] Requesting token for widget 0029
	Linie  674: 2023-09-30 14:03:20.978 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.aula
	Linie  675: 2023-09-30 14:03:20.981 DEBUG (MainThread) [custom_components.aula.sensor] Unique ID for child 1050096 aula1050096
	Linie  676: 2023-09-30 14:03:20.981 DEBUG (MainThread) [custom_components.aula.sensor] Unique ID for child 1050096 aula1050096
	Linie  677: 2023-09-30 14:03:20.981 DEBUG (MainThread) [custom_components.aula.sensor] Unique ID for child 1050096 aula1050096
	Linie  678: 2023-09-30 14:03:20.981 DEBUG (MainThread) [custom_components.aula.sensor] Setting state to n/a for child 1050096
	Linie  679: 2023-09-30 14:03:20.981 DEBUG (MainThread) [custom_components.aula.sensor] Could not get ugeplan for next week for child KID_1. Perhaps not available yet.

**Comment by scaarup** [comment]
okay, vi bliver nok lige nødt til at se hvad der bliver hentet fra MU. Kan indkommentere linje 262 og 263 i client.py og genstarte HA? Så skulle vi gerne logge svar ud.

**Comment by scaarup** [comment]
> Hej,
> 
> Jeg prøver også at få Aula integrationen op at køre, men kan desværre ikke se ugeplanerne, selvom jeg kan se dem i aula app'en.
> 
> Please answer the following:
> 
> Version of integration: 0.1.34 Version of Home Assistant: 2023.10.5 I have more than one child. 2 My children are attending different schools / institutions. Yes
> 
> Please provide debug log from the integration
> 
> This error originated from a custom integration.
> 
> Logger: custom_components.aula.client Source: custom_components/aula/client.py:253 Integration: Aula (documentation, issues) First occurred: October 29, 2023 at 1:24:20 PM (308 occurrences) Last logged: 2:58:16 PM
> 
> You have enabled ugeplaner, but we cannot find any matching widgets (0029,0004) in Aula.

Hej.

Du skriver på et eksisterende issue med en anden fejl. Du bør oprette et nyt.

Ugeplaner er et vidt begreb og loggen siger, der ikke kan findes nogen af dem integrationen understøtter. Du nævner ikke, eller viser ikke hvordan du ser ugeplaner i Aula, eller hvem der leverer dem. Så det eneste jeg kan sige er, at du nok har ugeplaner fra en tredjepart integrationen ikke understøtter.
