### ISSUE TITLE
http 410 response on API version

### ISSUE THREAD

**Issue by thomasfals** [scaarup/aula#120]
**Describe the bug or problem (In Danish is OK)**
Is it needed to write to the log when new api version is attempted? I mean it's expected behavior is it not? 

API was expected at https://www.aula.dk/api/v16 but responded with HTTP 410. The integration will automatically try a newer version and everything may work fine.

**Please answer the following**
- Version of integration: 0.1.34
- Version of Home Assistant: 2023.10.3

**Please provide debug log from the integration**
- Enable by adding the following to your configuration.yaml:
```

**Comment by scaarup** [comment]
No it is not needed to write anything in the log. When I look in my logs, it's 1 or 2 of these per day - not really a bug or an issue.
But are you suggesting to change the log-level to DEBUG for this particular line?

**Comment by thomasfals** [comment]
> No it is not needed to write anything in the log. When I look in my logs, it's 1 or 2 of these per day - not really a bug or an issue. But are you suggesting to change the log-level to DEBUG for this particular line?

That might be an idea. I guess I just prefer to keep a clear log for events that don't require any action.

**Comment by scaarup** [comment]
> > No it is not needed to write anything in the log. When I look in my logs, it's 1 or 2 of these per day - not really a bug or an issue. But are you suggesting to change the log-level to DEBUG for this particular line?
> 
> That might be an idea. I guess I just prefer to keep a clear log for events that don't require any action.

okay, I agree. I will make sure to get this change released with the next version.
