### ISSUE TITLE
Problemer med at se ugeplaner

### ISSUE THREAD

**Issue by cfsorensen** [scaarup/aula#123]
**Describe the bug or problem (In Danish is OK)**
Jeg ser ikke ugeplanen fra min søns skole, som den fremgår af Aula app'en.

Se vedhæftede billede:
![IMG_6930](https://github.com/scaarup/aula/assets/113860855/143c214c-7f40-4e57-afa1-b7251c58cc15)

Skyldes det at ugeplanerne leveres af Docendo?

**Please answer the following**
- Version of integration: 0.1.34
- Version of Home Assistant: 2023.10.5
- [x] I have more than one child
- [x] My children are attending different schools / institutions

**Please provide debug log from the integration**

This error originated from a custom integration.

Logger: custom_components.aula.client
Source: custom_components/aula/client.py:103
Integration: Aula (documentation, issues)
First occurred: 10:35:14 PM (1 occurrences)
Last logged: 10:35:14 PM

API was expected at https://www.aula.dk/api/v16 but responded with HTTP 410. The integration will automatically try a newer version and everything may work fine.

This error originated from a custom integration.

Logger: custom_components.aula.client
Source: custom_components/aula/client.py:253
Integration: Aula (documentation, issues)
First occurred: 10:35:16 PM (3 occurrences)
Last logged: 10:35:27 PM

You have enabled ugeplaner, but we cannot find any matching widgets (0029,0004) in Aula.

**Comment by scaarup** [comment]
"Ugeplaner er et vidt begreb og loggen siger, der ikke kan findes nogen af dem integrationen understøtter. Du nævner ikke, eller viser ikke hvordan du ser ugeplaner i Aula, eller hvem der leverer dem. Så det eneste jeg kan sige er, at du nok har ugeplaner fra en tredjepart integrationen ikke understøtter."

Debug loggen vil vise dig hvilke widgets integrationen har fundet og debug log er altid interessant hvis du opretter et issue.
Desuden kan du fortælle hvem, der leverer ugeplaner og måske et screenshot af hvordan det ser ud i Aula?

**Comment by cfsorensen** [comment]
Hej,
Jeg havde lige misset hvordan "koden" virkede for at indmelde her. Beklager.
Nu er mit billeder og lidt beskrivende tekst blevet synligt i den oprindelige post.

**Comment by cfsorensen** [comment]
Hej,
Hvad kunne man gøre for at få understøttet Docendo ugeplaner?
Dbh
Christian

**Comment by scaarup** [comment]
Hej.
Det kræver tid, udvikling og test.
Jeg har, som nævnt, ikke hørt om den før, så der skal lidt flere forespørgsler til, før jeg kaster en masse tid efter det.
Men du er selvfølgelig meget velkommen til at bidrage til projektet selv.

**Comment by Milfeldt** [comment]
Hej @scaarup.

Det er så fedt med din integration!
Jeg får også "You have enabled ugeplaner, but we cannot find any matching widgets (0029,0004) in Aula" vores skole kører med EasyIQ, jeg mener ellers jeg har læst at det er understøttet?
Fejlen er den samme på HA på Debian Bookworm og på en helt frisk HAOS.
Skema og besked ved ulæste meddelelser virker fint,
Jeg VIRKELIG HADER at skulle logge ind på AULA og navigere rundt for at finde hvad jeg vil se ;-)

**Comment by scaarup** [comment]
> Hej @scaarup.
> 
> Det er så fedt med din integration! Jeg får også "You have enabled ugeplaner, but we cannot find any matching widgets (0029,0004) in Aula" vores skole kører med EasyIQ, jeg mener ellers jeg har læst at det er understøttet? Fejlen er den samme på HA på Debian Bookworm og på en helt frisk HAOS. Skema og besked ved ulæste meddelelser virker fint, Jeg VIRKELIG HADER at skulle logge ind på AULA og navigerer rundt for at finde hvad jeg vil se ;-)

Hej @Milfeldt.
Fejlen du ser giver fint mening. Der er ikke understøttelse for EasyIQ.
Hvis du er skarp i at fange nogle requests til EasyIQ, via din browsers Developer Tools, kan jeg måske implementere det i integrationen.
Hvis du vil videre med det, må du helle oprette et nyt issue.

**Comment by Milfeldt** [comment]
AHA! 
Jamen så må jeg hellere begive mig ud i at lære noget nyt og finde ud af hvad jeg ser på ...

**Comment by scaarup** [comment]
> AHA! Jamen så må jeg hellere begive mig ud i at lære noget nyt og finde ud af hvad jeg ser på ...
> 
> Holy fckn cra ... @scaarup Jeg sad lige og kiggede den igennem med udviklerværktøjer, når man ikke lige ved hvad man specifikt skal finde, sååeh. Men øehh ... Ville du hurtigt kunne finde det hvis du kom på via Teamviewer :-)

Her en lille instruks:
Log ind på aula.dk
Højreklik hvor som helst og vælg "Inspect":
![image](https://github.com/scaarup/aula/assets/8055470/cb5d7448-befb-41a9-a5da-483055704824)
Hop over på "Network" tab'en og refresh hele siden. Her vil du så se alle de kald der laves og du skulle også kunne finde nogle kald til EasyIQ. Når du har fundet den/de kald, der giver mening, så højreklik og vælg "copy as curl cmd". 
![image](https://github.com/scaarup/aula/assets/8055470/7143a99b-2395-4cb4-89e2-59e1eecfcdfc)
Det du får kopieret må du gerne sætte herind i code tags.
Men igen - opret gerne et issue specifikt til det her.

**Comment by bipsendk** [comment]
Har netop efter seneste opdatering set, at jeg heller ikke får ugeplanen frem for mine børn...

**Comment by scaarup** [comment]
@bipsendk kan du uddybe lidt? Måske dele lidt debug logs, fortælle hvorfra du forventer at få ugeplaner (MinUddannelse ugenoter?)

**Comment by bipsendk** [comment]
@scaarup  Jeg kunne tidligere se ugeplan/noter fra Minuddannelse - de ser ikke ud til at være synlige lige nu

**Comment by scaarup** [comment]
Debug log tak.

Kan du bekræfte, at det virker hvis du er på version v0.1.37 ?

**Comment by bipsendk** [comment]
Så skal jeg lige hitte ud af at få en ældre version på ;-)
Jeg får lige lavet en debug log...

**Comment by bipsendk** [comment]
[Aula_0.1.37.log](https://github.com/scaarup/aula/files/14600366/Aula_0.1.37.log)

**Comment by bipsendk** [comment]
Status på sensor:
![image](https://github.com/scaarup/aula/assets/8531428/ceade8b9-cf5e-4457-b9f8-95ec96b9efae)

**Comment by Milfeldt** [comment]
Jeg kopierede client.py fra v0.1.37 over i den på HA installerede v0.1.38, så kører ugeplanerne igen

**Comment by scaarup** [comment]
Okay der er noget interessant her:
Child ids and names: {1069377: 'Marie Panduro Ipsen', 1694378: 'Mette Panduro Ipsen'}

Nu dukker samme barn op med flere forskellige profiler og det er måske kun den ene af dem, der har opgaver/ugeplan tilknyttet.

**Comment by bipsendk** [comment]
Ikke samme barn...Mette & Marie :-)

**Comment by scaarup** [comment]
Skulle være løst nu.
