### ISSUE TITLE
No data received from Aula

### ISSUE THREAD

**Issue by cfsorensen** [scaarup/aula#126]
**Describe the bug or problem (In Danish is OK)**
Jeg får ingen data igennem hverken kalender, ugeplan eller sensor.

**Please answer the following**
- Version of integration: 0.1.34
- Version of Home Assistant: 2023.10.5
- [x] I have more than one child
- [x] My children are attending different schools / institutions

**REQUIRED! Provide debug log from the integration**
- Enable by adding the following to your configuration.yaml:
```
logger:
  default: info
  logs:
    custom_components.aula: debug
```
- Restart Home Assistant
- Capture all log lines (from the integration only), save it to a file and attach it to here.

Logger: homeassistant.config_entries
Source: config_entries.py:565
First occurred: 8:17:05 PM (1 occurrences)
Last logged: 8:17:05 PM

Error unloading entry Aula for aula
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 565, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aula/__init__.py", line 44, in async_unload_entry
    hass.data[DOMAIN][entry.entry_id]["unsub_options_update_listener"]()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 680, in <lambda>
    return lambda: self.update_listeners.remove(listener)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: list.remove(x): x not in list

Logger: homeassistant.config_entries
Source: config_entries.py:565
First occurred: November 5, 2023 at 4:04:08 PM (2 occurrences)
Last logged: 8:17:05 PM

Error unloading entry Aula for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 565, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 132, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

**Comment by scaarup** [comment]
Debug log?

**Comment by cfsorensen** [comment]
@scaarup, jeg troede faktisk at det var debug logs jeg havde delt. Bær over med mig. Jeg har gjort følgende. Hvad har jeg gjort forkert ift. at dele log?

1. Kode tilføjet til config yaml:
`logger:
  default: info
  logs:
    custom_components.aula: debug`

2. HA restarted

3. Jeg er herefter gået til HA: Settings > System >Logs - Her har jeg fundet de fejl der var relateret til Aula (fx nedenstående) og kopieret fejl-koden i mit oprindelige indlæg.
![image](https://github.com/scaarup/aula/assets/113860855/ce102f5a-27f7-4a42-9c6e-364e29d3d7f2)

Deler jeg indhold fra en forkert log?

**Comment by scaarup** [comment]
Når du siger "fundet de fejl" - så kigger du kun efter "ERROR" ? Debug log er ikke fejl - det er debug. Hvis du søger på aula i HA: Settings > System >Logs, burde du finde alle logs relateret.

**Comment by cfsorensen** [comment]
Ok, jeg ser kun to entries relateret til Aula og de har begge "error" status:

**Logger: homeassistant.setup
Source: setup.py:359
First occurred: 6:20:09 AM (5 occurrences)
Last logged: 6:24:58 AM**

Unable to prepare setup for platform aula.sensor: Platform not found (Exception importing custom_components.aula.sensor).
Unable to prepare setup for platform aarlo.binary_sensor: Unable to set up component.
Unable to prepare setup for platform aarlo.sensor: Unable to set up component.
Unable to prepare setup for platform aarlo.alarm_control_panel: Unable to set up component.
Unable to prepare setup for platform aarlo.camera: Unable to set up component.

**Logger: homeassistant.loader
Source: loader.py:838
First occurred: 6:20:09 AM (1 occurrences)
Last logged: 6:20:09 AM**

Unexpected exception importing platform custom_components.aula.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 838, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 855, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/aula/sensor.py", line 10, in <module>
    from .client import Client
  File "/config/custom_components/aula/client.py", line 13
    frontend:
             ^
SyntaxError: invalid syntax

**Comment by scaarup** [comment]
Hvordan kører du egentlig Home Assistant?

**Comment by cfsorensen** [comment]
Jeg kører Home Assistant "direkte" på en Raspberry Pi 4.

**Comment by scaarup** [comment]
Det har helt sikkert noget med det at gøre. Jeg kan ikke rigtig hjælpe dig med det.

**Comment by cfsorensen** [comment]
Hej,
Understøttes "Home Assistant OS" måden at køre HA ikke? Såvidt jeg kan se er det én af de måder som HA anbefaler at køre med.
Problemet har umiddelbart løst sig selv efter at jeg opdaterede til nyeste version af integrationen.

**Comment by scaarup** [comment]
Hej.
Jo, jeg kører selv HAOS, men det er jo ikke det du gør?
Men lidt mærkeligt, at problemet er løst - der er ikke lavet andet end lidt småting i den nye release.
