### ISSUE TITLE
Lektier

### ISSUE THREAD

**Issue by OlNissen** [scaarup/aula#127]
Er det muligt at lave så man kan se data fra "min uddannelse - opgaver"?

Det er der hvor vores skole ligger lektier ind og børnene kan "strege" dem når de har lavet dem.

**Comment by scaarup** [comment]
Det er det højst sandsynligt. Men det er ikke et "modul/widget" jeg selv har adgang til, så det er en ret så omstændig process hvor du skal lave en del tests, samt hive data ud fra din browsers developer tools osv.

**Comment by scaarup** [comment]
Men vi har jo data fra MU Opgaver.
