### ISSUE TITLE
Sleep status no longer registers

### ISSUE THREAD

**Issue by xaviondk** [scaarup/aula#128]
**Describe the bug or problem (In Danish is OK)**

Jeg bruger integrationen til at få en notifikation når knægten vågner fra middagslur i vuggestuen. Men siden 11. Januar bliver "Sover" status ikke længere registreret. 

Frygter at Aula har ændret eller andet, for alle andre status bliver stadig registreret korrekt. F.eks kommet, gået, osv. 

Logger man ind i Aula kan man godt se derinde at barnet er lagt til middagslur, men den får ikke den ene status med over i HA

**Please answer the following**
- Version of integration:
- Version of Home Assistant: 
- [ ] I have more than one child
- [ ] My children are attending different schools / institutions

**REQUIRED! Provide debug log from the integration**
- Enable by adding the following to your configuration.yaml:
```
logger:
  default: info
  logs:
    custom_components.aula: debug
```
- Restart Home Assistant
- Capture all log lines (from the integration only), save it to a file and attach it to here.

**Comment by scaarup** [comment]
Hej @xaviondk.
Vi bliver nødt til at se noget debug log.
