### ISSUE TITLE
[Question] - Is it possible to see your username in any config files?

### ISSUE THREAD

**Issue by Aephir** [scaarup/aula#136]
I think I need to change unilogin password, but my girlfreind can't remember her username to do so (we need to use hers, since we have one "shared" kid, and two from her previous relationship that I can't see in my Aula).

If she tries to log in with MitID on Unilogin to get the username, it keeps throwing an error, while if I do the exact same, I get through. 

So, is the username that is logged in to the integration found in any config file anywhere, so we can use that to request a new password?

**Comment by scaarup** [comment]
Yes you can see it in: config/.storage/core.config_entries. An entry like:

```json
      {
        "entry_id": "9c1bc96373dc255ffd032e7aa185302f",
        "version": 1,
        "minor_version": 1,
        "domain": "aula",
        "title": "Aula",
        "data": {
          "username": "XXXXXXXX",
          "password": "XXXXXXXX",
          "schoolschedule": true,
          "ugeplan": true
        },
        "options": {},
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": null,
        "disabled_by": null
      }
```

But this here, really should work: https://viden.stil.dk/pages/viewpage.action?pageId=93487572#expand-ForldreogansattesamtelevermedMitID

**Comment by Aephir** [comment]
> But this here, really should work

Yes, it worked for my unilogin, but not my girlfriends. Go figure... But:

> config/.storage/core.config_entries

This worked, and we could change the password and re-integrate. Thanks!
