### ISSUE TITLE
Tilføj exempel på liste af beskeder

### ISSUE THREAD

**Issue by newbenji** [scaarup/aula#150]
Er ret ny i det her ha.
Og har lige integreret fint med aula for vores indtil videre ene barn i skolen.
OG fik fint ugeplan og calender ind, udfra dit exempel.

Men har du exempel på hvordan du laver den liste af beskeder med fold evt?

**Comment by scaarup** [comment]
Hej.
Du kan ikke lave en liste af beskeder, for integrationen vil kun vise dig en enkelt besked - den nyeste ulæste.

**Comment by newbenji** [comment]
ok ærgeligt. bare luk den her så
