### ISSUE TITLE
Ingen data siden 28. Maj

### ISSUE THREAD

**Issue by xaviondk** [scaarup/aula#165]
**Describe the bug or problem (In Danish is OK)**

Integrationen laver fejl og henter ikke længere data. 
![Screenshot_20240529_142735_Home Assistant](https://github.com/scaarup/aula/assets/68909910/320e9015-fb68-4c30-a3f1-09f20d844605)

**Please answer the following**
- Version of integration:
- Version of Home Assistant: 
- [ ] I have more than one child
- [ ] My children are attending different schools / institutions

**REQUIRED! Provide debug log from the integration**
- Enable by adding the following to your configuration.yaml:
```
logger:
  default: info
  logs:
    custom_components.aula: debug
```
- Restart Home Assistant
- Capture all log lines (from the integration only), save it to a file and attach it to here.

**Comment by scaarup** [comment]
Du svarer ikke på de spørgsmål der bliver stillet i template'en og du har ikke leveret debug log. Jeg ved ikke hvordan du tænker jeg skal kunne undersøge noget på baggrund af det screenshot du har vedhæftet?

**Comment by xaviondk** [comment]
> Jeg havde også problemer med Aula i går, og fik følgende fejl:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
>     self.data = await self._async_update_data()
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
>     return await self.update_method()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/aula/sensor.py", line 60, in async_update_data
>     await hass.async_add_executor_job(client.update_data)
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/aula/client.py", line 373, in update_data
>     self.get_widgets()
>   File "/config/custom_components/aula/client.py", line 183, in get_widgets
>     detected_widgets = self._session.get(
>                        ^^^^^^^^^^^^^^^^^^
> KeyError: 'moduleWidgetConfiguration'
> ```
> 
> Jeg kunne se det havde noget med Ugeplaner at gøre, så jeg geninstallerede bare Aula og slog `Ugeplaner` fra under installationskonfigurationen, da det alligevel ikke var relevant for mig - så kørte det fint igen.

Det virkede at slå ugeplaner fra. Tak.
