### ISSUE TITLE
Ingen data i ugeplanerne

### ISSUE THREAD

**Issue by LauWs** [scaarup/aula#166]
**Describe the bug or problem (In Danish is OK)**

Da jeg først installerede dette addon, så fik vi ugeplan nok så fint ind.
På et eller andet tidspunkt er det holdt op med at virke.
Jeg har slettet det og installeret igen og sat det op forfra uden held.
Er ikke en haj til det med logging, så hvis der mangler noget må du lige sige til.

Nu ser det således ud:
![image](https://github.com/scaarup/aula/assets/11090754/eb9e25c5-3d4e-4bd7-ab23-587c7496d1b4)

**Please answer the following**
- Version of integration: v0.1.39
- Version of Home Assistant: 
- Core: 2024.6.0.
- Supervisor: 2024.06.0
- OS: 11.4
- [X] I have more than one child

- [ ] My children are attending different schools / institutions

**REQUIRED! Provide debug log from the integration**
- Enable by adding the following to your configuration.yaml:
```
logger:
  default: info
  logs:
    custom_components.aula: debug
```
- Restart Home Assistant
- Capture all log lines (from the integration only), save it to a file and attach it to here.
- 
[home-assistant_2024-06-07T17-23-20.972Z.log](https://github.com/user-attachments/files/15743023/home-assistant_2024-06-07T17-23-20.972Z.log)

**Comment by Uberpainer** [comment]
Jeg hopper lige med her også, har har samme problematik og det eneste der virker for mig er at gå tilbage til version 0.1.36. Så bliver ugeplaner fetched igen. Det handler om min søn Asger der nævnes i loggen.

[home-assistant_aula_2024-06-08T07-58-56.717Z.log](https://github.com/user-attachments/files/15747254/home-assistant_aula_2024-06-08T07-58-56.717Z.log)

**Comment by lauer** [comment]
Jeg havde måske samme problem, men da mit kodeord til unilogin var udløbet, var det nok grunden.

Efter jeg nulstillede det via nemid https://mitunilogin.stil.dk/ - og genkonfigurerede aula i devices igen, fik jeg det hele indlæst. Både kalender og ugeplan.

**Comment by victordk** [comment]
Tænker ikke at det er udfordringen når jeg har gå og komme data der fint opdaterer og data på om der er en ny besked. Det oprindelige problem med at når opgaver og ugeplaner begge er aktive i min uddannelse - så vælger den det forkerte datasæt består.

**Comment by ccj2740** [comment]
Jeg har samme problem nu, men har ellers altid virket.
Er det mon AULA , som har problemer eller ?

**Comment by scaarup** [comment]
Hey alle.

Beklager ventetiden. Jeg har langt om længe forsøgt mig med, at splitte MU Opgaver op og ud af "ugeplaner". Så nu skal man enable MU Opgaver via config flow'et og MU Opgaver bliver registreret under sine egne sensor attributes. Dvs. det heller ikke længere skal konflikte med MU Ugeplaner.
Vil I prøve at teste dette ved at hive branch "issue_166" ud, slette Aula integrationen, sætte den op på ny?

Mange tak.

**Comment by Uberpainer** [comment]
> Hey alle.
> 
> Beklager ventetiden. Jeg har langt om længe forsøgt mig med, at splitte MU Opgaver op og ud af "ugeplaner". Så nu skal man enable MU Opgaver via config flow'et og MU Opgaver bliver registreret under sine egne sensor attributes. Dvs. det heller ikke længere skal konflikte med MU Ugeplaner. Vil I prøve at teste dette ved at hive branch "issue_166" ud, slette Aula integrationen, sætte den op på ny?
> 
> Mange tak.

Jeg får MU ugeplanner ind, men hele opsætningen fejler hvis jeg prøver at også at inkludere MU Opgaver.

**Comment by scaarup** [comment]
Tak @Uberpainer for test. 

Og du har også widget 0030? Jeg har nemlig ikke, så kan ikke rigtig teste det.

**Comment by Uberpainer** [comment]
@scaarup , nu spørger jeg måske dumt, men hvad er widget 0030?

**Comment by scaarup** [comment]
0030 er for MU Opgaver. Det er noget din institution/skole skal have tegnet en aftale om. Når Aula integrationen starter op, så står der hvilke widgets, der er fundet.
Ref.: https://aulainfo.dk/guide-til-projektledere/widgets-i-aula/

**Comment by Uberpainer** [comment]
Ja jeg har widget 0030
2024-09-20 09:44:42.564 DEBUG (SyncWorker_3) [custom_components.aula.client] Widgets found: {'0072': 'MU Elev - fravær', '0013': 'Nyttige links', '0023': 'MinUddannelse - SSO', '0028': 'MinUddannelse – Forløb', '0029': 'MinUddannelse – Ugenoter', '0035': 'KMD Educa Elev - Mit Barns Karakterer', '0030': 'MinUddannelse - Opgaver', '0069': 'KMD Educa Elev - Kontaktoplysninger'}

**Comment by scaarup** [comment]
@Uberpainer ups, my bad.
Gider du hente seneste rettelse ned og teste igen? 
Mange tak.

**Comment by Uberpainer** [comment]
> @Uberpainer ups, my bad. Gider du hente seneste rettelse ned og teste igen? Mange tak.

Sådan, nu får jeg ingen fejl når jeg både konfigurerer til både at hente opgaver og ugenoter.

Tusind tak for den tid du putter i det her, det er virkelig gudsgave, til den der ikke dagligt ønsker åbne Aula :D

Nu er der kun den her tilbage, meen det er noget helt andet :)

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 20:07:57 (2 occurrences)
Last logged: 20:08:03

Detected that custom integration 'aula' calls async_forward_entry_setup for integration, aula with title: Aula and entry_id: 01J889X1QNNH01MKB34M7EPDPW, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/aula/__init__.py, line 21: hass.async_create_task(, please create a bug report at https://github.com/scaarup/aula/issues
Detected that custom integration 'aula' calls async_forward_entry_setup for integration, aula with title: Aula and entry_id: 01J889X1QNNH01MKB34M7EPDPW, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/aula/sensor.py, line 97: hass.async_create_task(, please create a bug report at https://github.com/scaarup/aula/issues

**Comment by scaarup** [comment]
Fedt 👍🏻 og selv tak - det er godt det kan bruges 🙂

Til sidstnævnte - tak for det. Jeg blev opmærksom på det den anden dag og der er et issue på det allerede.

@LauWs du har oprettet det her issue, vil du også verificere før det bliver releaset?

**Comment by victordk** [comment]
Vil også bekræfte at ugeplaner virker her efter skift til issue_166 branchen. Fedt tak!

**Comment by LauWs** [comment]
> Fedt 👍🏻 og selv tak - det er godt det kan bruges 🙂
> 
> Til sidstnævnte - tak for det. Jeg blev opmærksom på det den anden dag og der er et issue på det allerede.
> 
> @LauWs du har oprettet det her issue, vil du også verificere før det bliver releaset?

Det kan du tro!
Kan du kort forklare hvordan jeg skifter til issue_166? :-)
Kiggede på det da du først skrev, men så kom jeg fra det og aner ikke lige hvad jeg skal.

Mvh.
René.

**Comment by LauWs** [comment]
> Fedt 👍🏻 og selv tak - det er godt det kan bruges 🙂
> 
> Til sidstnævnte - tak for det. Jeg blev opmærksom på det den anden dag og der er et issue på det allerede.
> 
> @LauWs du har oprettet det her issue, vil du også verificere før det bliver releaset?

Ah my bad! Skulle lige installere samba og så manuelt installere den :)
Det virker!

**Comment by scaarup** [comment]
Fedt @LauWs 👌🏻
Jeg laver en "rigtig" release på det lidt senere.

**Comment by ebbeflarup** [comment]
Lige hurtig FYI @scaarup , denne linie vil få huskelisten til at fejle:
https://github.com/scaarup/aula/compare/main...issue_166#diff-c7c2ba039ce2a226bd0a344b89079b2cddd208dc23af0de07405bffac3fe3ebcL615

'zone' headeren er påkrævet.

<img width="1130" alt="Screenshot 2024-09-26 at 22 25 37" src="https://github.com/user-attachments/assets/9450942b-646d-43a4-bbbf-58d460ef8290">

**Comment by victordk** [comment]
> Fedt @LauWs 👌🏻 Jeg laver en "rigtig" release på det lidt senere.

Er denne med i 0.1.44 ?

**Comment by scaarup** [comment]
Nej sorry - jeg skal nok få taget mig sammen her i weekenden og få det merged.

**Comment by scaarup** [comment]
> 0.1.44

Du må meget gerne teste 0.1.45

**Comment by victordk** [comment]
> > 0.1.44
> 
> Du må meget gerne teste 0.1.45

Det virker fint. Tak.
