### ISSUE TITLE
Error requesting sensor data: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by victordk** [scaarup/aula#169]
**Describe the bug or problem (In Danish is OK)**

Integrationen starter op uden data i entiteter - får en fejl i systemloggen. Se nedenstående.

**Please answer the following**
- Version of integration: 0.1.39
- Version of Home Assistant: 2024.7.3
- [ x] I have more than one child
- [ x] My children are attending different schools / institutions

**REQUIRED! Provide debug log from the integration**
- Enable by adding the following to your configuration.yaml:
```
logger:
  default: info
  logs:
    custom_components.aula: debug
```
- Restart Home Assistant
- Capture all log lines (from the integration only), save it to a file and attach it to here.

[log.txt](https://github.com/user-attachments/files/16328364/log.txt)

**Comment by scaarup** [comment]
Prøv lige at sæt integrationen op på ny, men uden ugeplaner.

**Comment by victordk** [comment]
Så virker den - men kommer da til at savne ugeplanerne :)

**Comment by scaarup** [comment]
Jeg er ramt af samme problem og nu efter lidt debugging lader det til, at det er pga vedligehold. 
![image](https://github.com/user-attachments/assets/88c60c0f-3f94-4ff7-bece-1d879d1a20f3)
Jeg må nok hellere få lavet lidt fejlhåndtering på det.

**Comment by victordk** [comment]
Har lige prøvet med 0.1.40 - får følgende fejl: 

[log2.txt](https://github.com/user-attachments/files/16334517/log2.txt)
