### ISSUE TITLE
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for aula doing blocking calls at custom_components/aula/calendar.py, line 38: time.sleep(0.400)

### ISSUE THREAD

**Issue by thomaspalmdk** [scaarup/aula#18]
Med høje forventninger installerede jeg denne integration :-)
Har genstartet HA et par gange, men i min log har jeg et par fejl - måske er de uden betydning?
Anyways; jeg laver lige et issue på hver af fejlene.

Snip direkte fra HA-loggen:

```
Logger: homeassistant.util.async_
Source: util/async_.py:180
First occurred: 20.02.09 (6 occurrences)
Last logged: 20.02.11

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for aula doing blocking calls at custom_components/aula/calendar.py, line 38: time.sleep(0.400)
```

**Comment by scaarup** [comment]
Yes, det her er jeg klar over. Det er kun en warning. I calendar.py er jeg afhængig af noget data og jeg har ikke fået lavet en god måde at vente på, at data bliver tilgængelig. 
Der kommer et fix snarest.
Tak.

**Comment by scaarup** [comment]
This is resolved in v0.1.24
