### ISSUE TITLE
Cannot update in HA

### ISSUE THREAD

**Issue by Oldefa1985** [scaarup/aula#181]
Jeg kan ikke længere opdatere min integration i Home Assistant

![image](https://github.com/user-attachments/assets/16f7542b-0872-492f-b40b-fc9c4134fcfe)

Trykker bare update, der er forsøgt genstart mv. og netværksindstillinger er korrekte.

**Comment by Roagert** [comment]
jeg har samme issue

**Comment by Oldefa1985** [comment]
> Der var lidt bøvl med releases og github actions i går. Der er en 0.1.42 ude - virker den?

Den virker ;) takker
