### ISSUE TITLE
Cannot download v. 0.1.41

### ISSUE THREAD

**Issue by AndreasHerss** [scaarup/aula#183]
HACS cannot find the file to download, resulting in update failing. 

Log info: <Integration scaarup/aula> Failed to download https://github.com/scaarup/aula/releases/download/tags/v0.1.41/aula.zip

Github is returning a 404 not found. 
According to the release (https://github.com/scaarup/aula/releases/tag/v0.1.41) the assets is not bundled, only sourcecode zips. 

Edit: I just saw the 0.1.42 pre-release contains the aula.zip file, guess it will be resolved when that version is released then.

**Comment by scaarup** [comment]
Pls go with 0.1.42
