### ISSUE TITLE
Login for medarbejder+forældre

### ISSUE THREAD

**Issue by sorentorp** [scaarup/aula#24]
Super godt arbejde!

Når en person både er medarbejder og forældre med uni-login, virker denne integration ikke. Jeg formoder at det handler om denne mini-broker, som afkræver et rollevalg. Måske det kan indarbejdes? Jeg vedlægger den url jeg lander på, screenshot og kildekoden til siden.

`https://broker.unilogin.dk/auth/realms/broker/login-actions/post-broker-login?client_id=https%3A%2F%2Fprod-uni.aula.dk%2Fsimplesaml%2Fsaml2%2Fidp%2Fmetadata.php&tab_id=QfHrn1LoZZw`

[Pastebin med kildekoden](https://pastebin.com/fCizcu0K)

![Screenshot 2022-11-12 16 36 18](https://user-images.githubusercontent.com/4117997/201482014-99f166eb-29f4-4cfd-8af3-c162e500ab0e.png)

Skriv endelig hvis der er mere data jeg kan hjælpe med.

**Comment by scaarup** [comment]
Hejsa.

Vil du prøve med denne her branch: https://github.com/scaarup/aula/tree/24-login-for-medarbejder%2Bfor%C3%A6ldre
Og slå debug logging til på denne integration.

Det er lidt et long-shot, når man ikke lige kan teste det selv ;).

**Comment by sorentorp** [comment]
Done - håber det kan bruges.

[Debug 1](https://pastebin.com/9mWuZZzr)

[Debug 2](https://pastebin.com/9WsF0TS4) 

[Debug 3](https://pastebin.com/6JXcPJaz)

**Comment by scaarup** [comment]
Der er desværre ikke en eneste debug log linje. Vil du slå debug på integrationen, genstart HA og give mig alt det, der står aula på?

```
logger:
  default: info
  logs:
    custom_components.aula: debug
```

**Comment by sorentorp** [comment]
synes ellers jeg havde aktiveret debug, men din metode virker :-)

[debug](https://pastebin.com/uxv53QFk)

**Comment by scaarup** [comment]
Gider du pull'e de seneste ændringer på branchen (https://github.com/scaarup/aula/tree/24-login-for-medarbejder%2Bfor%C3%A6ldre) og prøve igen?

**Comment by sorentorp** [comment]
Så er der nyt - no luck...

[debug](https://pastebin.com/zaWrifuB)

**Comment by scaarup** [comment]
Tror ikke du har fået hentet den branch. Der står 
"Aula integration, version: 0.1.15" i din log, og jeg har rettet versionen til "0.1.15b".

**Comment by sorentorp** [comment]
rigtigt - nu fik jeg den ned. De er den ikke glad for.

`2022-11-13 00:08:32.160 ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'aula' does not have a valid version key (0.1.15b) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details`

**Comment by scaarup** [comment]
Ah okay. Så kan du selv lige lave versions strengen om.

**Comment by sorentorp** [comment]
Tjek - den blev bare til 0.1.15 :-)

[debug](https://pastebin.com/HPd4tE3i)

**Comment by scaarup** [comment]
Jeg kan ikke finde den form i noget af det vi får serveret.

Jeg har opdateret branch'en med meget mere debug log, så må du gerne lige prøve igen. Vi logger al HTML ud, så det bliver nok til en del.

**Comment by sorentorp** [comment]
Det blev da til en smule :-)

[debug](https://pastebin.com/ubmtvZWm)

**Comment by scaarup** [comment]
Tak :)

Det er meget meget svært når jeg ikke kan teste det her selv.

Er du hjemme i Developer tools i din browser? Kan du mon fange (copy as curl), den POST hvor du vælger, at du er logger ind som forældre?

**Comment by sorentorp** [comment]
ja da - tror det er 2'eren du er ude efter.

[nr 1](https://pastebin.com/nFFvG4xy)
[nr 2](https://pastebin.com/fDrKkeBB)
[nr 3](https://pastebin.com/zk5dgbSJ)
[nr 4](https://pastebin.com/5pipMdrh)
[nr 5](https://pastebin.com/cTitrtzf)

**Comment by scaarup** [comment]
Perfekt tak.

Vil du prøve at opdatere til de seneste ændringer fra branchen (https://github.com/scaarup/aula/tree/24-login-for-medarbejder%2Bfor%C3%A6ldre)?
Version skulle gerne sige "0.1.1337" når du starter den op.

**Comment by sorentorp** [comment]
så er der nyt

[debug](https://pastebin.com/qYPkAVQ6)

**Comment by scaarup** [comment]
Jeg har ikke flere skud i bøssen...

Med mindre jeg kan få fat på et login som dit, kan jeg ikke rigtig komme videre desværre.

**Comment by sorentorp** [comment]
Hvis du har tid i morgen over middag, kan vi evt sætte et lille møde op? Skriv på "soren . Torp @ Gmail . Com"

**Comment by scaarup** [comment]
Jeg tror desværre der skal mere end et møde til. Det kræver, at man bruger en hel del tid på at reverse hele login flowet. En masse tests og en masse tid.

**Comment by sorentorp** [comment]
Okay, det er jo fair nok. De fleste der arbejder i en skole eller en børnehave har vel en bedre halvdel, som ikke gør 😀

**Comment by JBoye** [comment]
Har i set:
https://github.com/JBoye/HA-Aula/issues/4#issuecomment-1007291754

Det lyder til at de knækkede den

**Comment by scaarup** [comment]
> Har i set:
> https://github.com/JBoye/HA-Aula/issues/4#issuecomment-1007291754
> 
> Det lyder til at de knækkede den

Ah ja, det var da interessant 🙂. @sorentorp vil du give det et skud?

**Comment by sorentorp** [comment]
@scaarup er der et nyt branch jeg skal teste, eller hvad er det jeg skal give et skud? :-)

**Comment by scaarup** [comment]
> @scaarup er der et nyt branch jeg skal teste, eller hvad er det jeg skal give et skud? :-)

Det var specifikt denne løsning, der var refereret til:
![image](https://user-images.githubusercontent.com/8055470/203499455-573fbdc3-4024-4a70-9e78-ec52b2f9fddd.png)

Ændre user_data i client.py til:
```
user_data = { 'username': self._username, 'password': self._password, 'selected-aktoer': "KONTAKT" }
```

**Comment by sorentorp** [comment]
Det virker :-)

**Comment by scaarup** [comment]
> Det virker :-)

Perfekt 👍

**Comment by scaarup** [comment]
Der er et fix med i v0.1.21, som er ude i pre-release nu.
