### ISSUE TITLE
Ingen sensorer, kun kalender

### ISSUE THREAD

**Issue by dennisnn87** [scaarup/aula#38]
Jeg får ikke nogen sensorer ind når jeg kører integrationen. Kalender delen virker dog fint. 

<img width="1282" alt="Skærmbillede 2022-11-22 kl  11 57 28" src="https://user-images.githubusercontent.com/104697675/203297147-16172fdb-acc3-4f47-b8f8-431999ff38e8.png">

**Comment by scaarup** [comment]
Denne fejl er allerede rapporteret i issue #17.
```
Unexpected error fetching sensor data: 'personer'
```
Du kan genopsætte integrationen uden "ugeplaner", indtil issue 17 er løst.
