### ISSUE TITLE
Feature request: Huskelisten fra Systematic

### ISSUE THREAD

**Issue by sorentorp** [scaarup/aula#42]
Super brugbar integration :-)

Hvad med at få huskeliste-elementerne indlæst, fra huskelisten som Systematic leverer til en del kommuner? Den ser således ud:

![Screenshot 2022-11-24 22 16 27](https://user-images.githubusercontent.com/4117997/203864307-23290f1b-d1e4-4f20-b4ae-e189071c7e28.png)

Koden for denne visning er således:
https://pastebin.com/1QwBmVHT

Skriv endelig hvis jeg kan sende/teste yderligere

**Comment by sorentorp** [comment]
Hej igen :-)

Yes, det er en visning i Aula. Se herunder.

![Screenshot 2022-11-25 09 56 54](https://user-images.githubusercontent.com/4117997/203941091-cd431823-5a1b-4c36-b8ad-b49bbb332709.png)

**Comment by scaarup** [comment]
Kan du lige prøve i din browsers developer tools, finde det kald til Huskelisten
- paste response herind
- højreklikke på det kald og "copy as curl". Paste her.

**Comment by sorentorp** [comment]
noget ala det her?

[link](https://pastebin.com/0m2GJZgj)

**Comment by sorentorp** [comment]
der er egentlig fire - måske det hjælper?

[link](https://pastebin.com/wdq3iDXG)

**Comment by scaarup** [comment]
Yes - husk lige at skjul det der bearer token en anden gang ;)

Jeg mangler at se noget response data også.

**Comment by sorentorp** [comment]
modtaget - håber ikke den har evig varighed :-) 

[håber det kan bruges](https://pastebin.com/FjpFYhHG)

**Comment by sorentorp** [comment]
Fist-bump 😉

**Comment by scaarup** [comment]
Jeg mangler selve svaret fra de requests. Jeg kunne også godt tænke mig at se din debug log pt. Ved opstart registrerer integrationen aula "widgets", så som Ugenoter fra meebook osv., så er interesseret i at vide om denne her Huskeliste også dukker op der.

**Comment by sorentorp** [comment]
Jeg har lagt response i det paste jeg lavede sidst - det er tre i én. Du får debug log senere

**Comment by scaarup** [comment]
Måske kan du også se om det er et kald til "?method=aulaToken.getAulaToken&widgetId=XXX" ?

**Comment by sorentorp** [comment]
Tjek - ny omgang [debug](https://pastebin.com/T4T1ZA42)

**Comment by sorentorp** [comment]
Så er der lidt nyt :-) Nu med ugeplaner aktiveret

[Debug](https://pastebin.com/RtRf1tqu)

**Comment by scaarup** [comment]
Tak @sorentorp - der står nu godt nok ```2022-12-06 22:08:51.033 DEBUG (SyncWorker_1) [custom_components.aula.client] Config - schoolschedule: True, config - ugeplaner: False```

**Comment by sorentorp** [comment]
argh, jeg har lige lavet en komplet fjern/tilføj.

[debug](https://pastebin.com/EKU07WAU)

**Comment by scaarup** [comment]
Tak perfekt. Så snakker vi med Huskelisten. 

Kan du lige prøve at udkommentere/fjerne linje 204 i client.py, starte op igen og lad os se hvad log-linjen "Huskelisten raw response" siger?

**Comment by sorentorp** [comment]
[debug](https://pastebin.com/Mib5tGWH)

**Comment by scaarup** [comment]
Er der noget nyt der er dukket op på linje 204, for denne fejl dukker stadig op:
```File "/config/custom_components/aula/client.py", line 204, in ugeplan```
Hvilket ikke skulle kunne lade sig gøre såfremt linje 204 er tom/udkommenteret :)

**Comment by sorentorp** [comment]
ahhhh, den 204 :-)

det var vist en and

[DEBUG](https://pastebin.com/q8CtDJ51)

**Comment by sorentorp** [comment]
[Nu begynder der at komme noget frem](https://pastebin.com/UwePVgs3)

**Comment by scaarup** [comment]
Vi får desværre stadig denne her "Internal Server Error" fra Huskelisten. 

Du må godt lige hive seneste ændring ned fra branchen og prøve igen. Jeg har hardcoded de argumenter vi sender til huskelisten nu - bare som test.
Hvis det stadig ikke virker, så i din browser, fange det request til huskelisten og "copy as curl"?
Der må være et eller andet jeg ikke får med.

**Comment by sorentorp** [comment]
Jeg håber at dette kan bruges - det er fra min browser. [pastebin](https://pastebin.com/JGcXpQA4)
Jeg har taget cURL og alle i toppen :-)
![Screenshot 2022-12-12 11 42 05](https://user-images.githubusercontent.com/4117997/207027323-a4e16826-fdb8-4cef-88c8-3e9b7a2443ce.png)

Her er også den visning, som passer til :-)
![Screenshot 2022-12-12 11 40 05](https://user-images.githubusercontent.com/4117997/207027270-3124c610-8754-4d7b-a1a0-8ce96bd423b4.png)

Jeg har desuden kørt den nye branch, her er log fra HASS.
[log](https://pastebin.com/QzEpYEfL)

Kan det bruges?

**Comment by scaarup** [comment]
Tak @sorentorp . Jeg har opdaget en brøler her fra min side. Vil du lige prøve med den seneste update?

**Comment by sorentorp** [comment]
[nu rykker det :-)](https://pastebin.com/yFvYS0SA)

**Comment by scaarup** [comment]
> [nu rykker det :-)](https://pastebin.com/yFvYS0SA)

Det kan jeg ikke se. Din log er også nogle timer gammel :)

**Comment by sorentorp** [comment]
[så nu da](https://pastebin.com/CP9Uyr8x)

**Comment by sorentorp** [comment]
![image](https://user-images.githubusercontent.com/4117997/207047535-b2fda9b5-af3b-4399-be37-efe9bfee52aa.png)

![image](https://user-images.githubusercontent.com/4117997/207047602-4e07e216-8143-468e-8d93-8b7d3b5205f7.png)

**Comment by scaarup** [comment]
Okay, er det som det skal være?

**Comment by sorentorp** [comment]
Data er korrekt, yes! Front-end i aula laver åbenbart noget filter på at den ikke viser data i fortiden, fx. det element fra d. 30/11. Men hvis de kan komme i kalender, er det jo fint.

Sådan her ser frontend ud. 
![image](https://user-images.githubusercontent.com/4117997/207048386-bc549a23-bc41-43ee-b589-70e5f77a225e.png)

**Comment by scaarup** [comment]
Jamen det var faktisk fordi jeg hardcoded din get Payload. Hvis du lige hiver seneste update fra branch'en, så håber jeg det virker fortsat og med emner fra dags dato til 180 dage i fremtiden.

Har du prøvet at visualisere den attribute i et markdown card i HA?

**Comment by sorentorp** [comment]
Har du et hurtigt eksempel på det? Det har jeg ikke prøvet før... 
sensor.holme_skole_navn

![image](https://user-images.githubusercontent.com/4117997/207057491-9877493d-632b-4538-9438-14942626365d.png)

**Comment by sorentorp** [comment]
Godt ord igen :-) Jeg kunne endda nøjes med endnu mindre. Så er det næste at filtrere på ting, som ikke er i fortiden... Det kan vel fixes som en del af visningen.

![Screenshot 2022-12-12 14 44 17](https://user-images.githubusercontent.com/4117997/207060103-d08eb722-cb4a-4a34-9b30-b0569fb9c5a8.png)

**Comment by scaarup** [comment]
Fedt - det ser meget lækkert ud :).

Har du hevet den seneste update ned? For der skulle gerne ikke være noget fra fortiden. Hvis ja, så vil jeg gerne lige se debug loggen.

**Comment by sorentorp** [comment]
[den er her :-)](https://pastebin.com/6wFHQtfp)

**Comment by scaarup** [comment]
Hvis du kigger efter "dueDate" i din log, er der ingen entries i fortiden. Dit markdown card burde også vise det samme?

**Comment by scaarup** [comment]
> [den er her :-)](https://pastebin.com/6wFHQtfp) - og nu kommer der heller ikke data fra datid :-)

perfekt :)

Hvordan med de der overskrifter til de enkelte dage, skal de være en anelse mindre?

**Comment by sorentorp** [comment]
*heller :-)

Det spiller

![Screenshot 2022-12-12 14 56 33](https://user-images.githubusercontent.com/4117997/207063375-700db156-43a7-47b8-b436-a7a456adf8b3.png)

**Comment by sorentorp** [comment]
Det må gerne være mindre, ja.

**Comment by scaarup** [comment]
> Det må gerne være mindre, ja.

Okay, det er rettet nu (til en html h3).

**Comment by sorentorp** [comment]
Godkendt - fin størrelse!

Er der andet jeg skal teste?

**Comment by scaarup** [comment]
> Godkendt - fin størrelse!
> 
> 
> 
> Er der andet jeg skal teste?

Fedt 👍. 

Nej ikke videre. Hvis du melder OK, så laver jeg en prerelease version.

**Comment by sorentorp** [comment]
Ok herfra - og mega mange tak for arbejdet!
