### ISSUE TITLE
[Feature request] Switches and sensors.

### ISSUE THREAD

**Issue by Aephir** [scaarup/aula#67]
for det første, tak, jeg er virkelig glad for denne integration!

Jeg har et par ønsker, hvis det er teknisk muligt.

1. Ville det være muligt at lave `switch` til f.eks. at melde ban syg, eller melde ferie?

Efter Aula (eller vores børnehave?) gjorde så barnet automatisk raskmeldes hver nat, så skal vi huske at melde syg igen hver morgen barnet er syg. Det kan helt sikkert automatiseres bedre gennem Home Assistant.

Det samme med ferier, som ville kunne læses af Home Assistant i kalendere (og/eller måske aula's kalender kunne eksponneres af integrationen?).

2. Ville det være muligt at få en sensor til beskeder modtaget i aula, så disse kunne komme ind i Home Assistant?

Så kunne få man f.eks. beskeden læst højt når man kommer hjem, e.l. Eller man kunne holde øje med "keywords" som f.eks. `husk`, `opkast`, `syg`, o.l., og sørge for at gøre ekstra opmærksom på disse.

**Comment by scaarup** [comment]
Mange tak :)

1. Det skulle nok nærmere være en eller flere services, der kunne kaldes til de formål. Jeg har selv tænkt på lidt det samme - oprette gå-hjem-tider fra SFO mv. Men jeg er lidt tilbageholdende, da en fejl fra min side kunne resultere i noget misinformation til skolen, eller måske i værste fald risikere at sende nogle unger hjem i utide :).
Jeg ved ej heller om der er 1 eller 10 måder, at melde et barn syg/ferie mv. Det skal i hvert fald undersøges først.

2. Ja det ville nok være muligt. Hvordan tænker du sådan praktisk? Jeg har fx rigtig mange beskeder, og beskeder bliver til tråde med svar - ofte meget lange. Man kunne måske have en sensor for den seneste ulæste besked el.lign.

**Comment by Aephir** [comment]
Ja, det kunne selvfølgelig hurtigt blive noget rod. Jeg ved ikke rigtig om jeg har så meget at bidage med andet end ønsket, men hvis du har noget specifikt jeg skal afprøve for dig, så gør jeg det gerne.

Måske det bare kunne være en `binary_sensor` som havde `state` værende om beskeden er ulæst i aula, og selve beskeden i attributes. 

Den ville så opdateres hver gang der kommer en ny, men en automation kan jo stadig nå at affyre selv hvis beskeden bliver "overskrevet" nogle sekunder eller minutter senere.

Ift. alle beskeder/tråde, de var ikke så relevante for hvad jeg umiddelbart havde i tankerne, men nu jeg tænker over det, måske man kunne lave en `service_call`, som kan returnere dem specifikt hvis man har brug for dem i stedet for altid at have en `entity` med en flere km lang `attribute`?

**Comment by scaarup** [comment]
Ja, det er gode forslag. Jeg prøver at tage et kig på det.

**Comment by Aephir** [comment]
Nu hvor jeg ser nærmere efter, kaldeneren fra aula kunne helt sikkert være rigtig god at have, selv hvis det bare blev en `sensor` eller noget man kan tilgå med et `service_call`.

For det er det eneste sted man med sikkerhed kan se hvad de skal have af fag (f.eks. idræt hvor de skal huske idrætstøj), da det ellers kun er hvis læreren direkte (manuelt) skriver i ugeplan. Eller hvis man opretter en kalender selv, med alt dette info. Men det virker lidt som dobbeltarbejde, især fordi skema nogle gange skifter midt på skoleåret, og helt sikkert hvert år.

**Comment by scaarup** [comment]
> Nu hvor jeg ser nærmere efter, kaldeneren fra aula kunne helt sikkert være rigtig god at have, selv hvis det bare blev en `sensor` eller noget man kan tilgå med et `service_call`.
> 
> For det er det eneste sted man med sikkerhed kan se hvad de skal have af fag (f.eks. idræt hvor de skal huske idrætstøj), da det ellers kun er hvis læreren direkte (manuelt) skriver i ugeplan. Eller hvis man opretter en kalender selv, med alt dette info. Men det virker lidt som dobbeltarbejde, især fordi skema nogle gange skifter midt på skoleåret, og helt sikkert hvert år.

Kalenderen i Aula har du allerede jo - det er der skoleskemaet kommer fra.

Ift. til beskeder fra Aula, så har jeg lavet denne branch, du gerne må teste: https://github.com/scaarup/aula/tree/messages-feature.

Der er en binary_sensor, der skifter såfremt der er en ulæst besked og selve emnet og beskeden er i attributes:
![image](https://user-images.githubusercontent.com/8055470/212015746-f071dba6-f091-4fe8-b67c-9ce861a927b7.png)

**Comment by Aephir** [comment]
Ups ja, det kan jeg godt se (kalender).

Jeg får ikke noget i besked sensor (er det fordi den først dukker op første gang der kommer en ny besked efter `binary_sensor` er oprettet?):

<img width="1068" alt="Screenshot 2023-01-13 at 10 18 43" src="https://user-images.githubusercontent.com/20152788/212284027-7879ef04-f066-42c2-89bf-a07a4dea48d8.png">

Forresten, hvis det kræver meget adgang til app for at verificere (f.eks. at `binary_sensor` opdaterer når der kommer en besked) kan det være jeg er lidt langsom. Jeg har integreret min kærestes uala, da den ældste af vores er hendes fra et tidligere forhold, og derfor ikke er i min aula.

**Comment by scaarup** [comment]
Er du helt sikker på, at du har ulæste beskeder i Aula? 
![image](https://user-images.githubusercontent.com/8055470/212291779-aa2e749d-99fb-4f4f-b0cb-0568bba8481f.png)

**Comment by Aephir** [comment]
Jeg har som sagt desværre ikke "direkte"adgang til den Aula vi bruger i HA, det er min kærestes (for at også hendes børn er der).

Jeg prøver at holde øje med `binary_sensor` de næste dage, og spørge hende ind i mellem om hun har fået nye beskeder.

**Comment by scaarup** [comment]
Perfekt 👍.
Jeg afventer din feedback, før vi releaser noget.

**Comment by Aephir** [comment]
Det ser ud til at det virker fint her:

<img width="571" alt="Screenshot 2023-01-13 at 13 01 39" src="https://user-images.githubusercontent.com/20152788/212315951-1ed6f901-f771-4f0e-8355-d21a584ffe23.png">

**Comment by scaarup** [comment]
Fedt 🙂

**Comment by scaarup** [comment]
Jeg har lige fundet en fejl. Lader til, at vi kun får den første del af beskeden i det kald jeg laver. Så der skal lige en rettelse til før vi får hentet hele beskeden. Jeg vender retur.

**Comment by Aephir** [comment]
Ja, var lige ved at nævne at enten havde læreren glemt at skrive tidspunkt, ellers manglede der noget af besked :)

**Comment by scaarup** [comment]
Ja det så jeg også :)

Jeg har lige pushet et fix op, du må gerne teste. (attribute indeholder nu også afsender)

Btw, hvis du vil vise et card med seneste besked, såfremt der er nogen:

![image](https://user-images.githubusercontent.com/8055470/212323496-1a38fb95-f82c-4606-a600-b9b59275a43a.png)

```yaml
type: conditional
conditions:
  - entity: binary_sensor.aula_aulamessage
    state: 'on'
card:
  type: markdown
  content: |-
    ## {{ state_attr('binary_sensor.aula_aulamessage', 'subject') }}
    ### Fra: {{ state_attr('binary_sensor.aula_aulamessage', 'sender') }}

    {{ state_attr('binary_sensor.aula_aulamessage', 'text') }}
```

**Comment by Aephir** [comment]
Det ser rigtig fint ud herfra!

**Comment by Aephir** [comment]
Lige en hurtig update, `binary_sensor.aula_aulamessage` blev på et tidspunkt `unavailable`. Det virkede ikke at sige `reload` from `integrations` siden, men hvis jeg slettede alt fra `custom_components/aula`, og kopierede den branch over igen, så var den der igen efter genstart.

Jeg er ikke sikker på om der har været en opdatering i HACS jeg er kommet til at installere uden at se ordentlig efter?

Under alle omstændigheder, så holder jeg fortsat øje med den, og siger til hvis jeg ser noget igen.

**Comment by scaarup** [comment]
Tak for feedback. 
Måske jeg også selv skulle få testet det ordentligt :)

**Comment by scaarup** [comment]
Holder den lige åben imens jeg tester. Pre-release out.

**Comment by Aephir** [comment]
Jeg tror det er når man genstarter Home Assistant at sensor ryger? Jeg ser i hvert fald at den bliver ved med at ende som 

<img width="588" alt="Screenshot 2023-01-23 at 10 14 45" src="https://user-images.githubusercontent.com/20152788/214052256-62844efd-f2cb-49fd-9ef4-3784fd2b4267.png">

Og ved genstart får jeg af og til denne:

```
Logger: homeassistant.components.binary_sensor
Source: custom_components/aula/binary_sensor.py:22
Integration: Binary sensor (documentation, issues)
First occurred: 14:45:39 (1 occurrences)
Last logged: 14:45:39

Error while setting up aula platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/aula/binary_sensor.py", line 22, in async_setup_entry
    device = AulaBinarySensor(hass=hass, unread=client.unread_messages, subject=subject, text=text, sender=sender)
UnboundLocalError: local variable 'sender' referenced before assignment

```

**Comment by Aephir** [comment]
v0.1.28 ser umiddelbart ud til at virke for mig.
