### ISSUE TITLE
binary_sensor.aula_aulamessage becomes unavailable after HA restart

### ISSUE THREAD

**Issue by Aephir** [scaarup/aula#79]
**Describe the bug or problem (In Danish is OK)**
sensoren så ud til at virke fint, men jeg opdagede efter en HA reboot at den var "unavailable".

I logs var der:

```
Error while setting up aula platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/aula/binary_sensor.py", line 14, in async_setup_entry
    subject = client.message["subject"]
KeyError: 'subject'
```

**Please answer the following**
- Version of integration: 0.1.29
- Version of Home Assistant:  2023.2.0
- [x] I have more than one child
- [x] My children are attending different schools / institutions

Og PS; jeg tror der er en typo et sted, da jeg gætter på `binary_sensor.aula_aulamessage` skulle hedde `binary_sensor.aula_message`

**Comment by SkinnyGnome** [comment]
Jeg har også problemet.
Jeg kører med samme versioner.

**Comment by scaarup** [comment]
Jeg kigger på det. 

Tak alle 🙂

**Comment by sorentorp** [comment]
same

**Comment by scaarup** [comment]
Ved I om I har ulæste beskeder i Aula - eller ingen ulæste beskeder?

**Comment by SkinnyGnome** [comment]
Hej,

Pt. har jeg 5 ulæste beskeder i AULA.

**Comment by scaarup** [comment]
> Hej,
> 
> Pt. har jeg 5 ulæste beskeder i AULA.

Okay perfekt - det ville også give mening ift. den fejl der er på at finde et "subject".

**Comment by scaarup** [comment]
Nogen, der er friske på at prøve denne her branch: https://github.com/scaarup/aula/tree/79-binary_sensoraula_aulamessage-becomes-unavailable-after-ha-restart ?
Gerne med debug log på.

**Comment by SkinnyGnome** [comment]
Jeg har installeret overstående Branch:

Jeg får følgende i Debug loggen omkring Aula:
[home-assistant_aula_2023-02-03T13-28-12.536Z.log](https://github.com/scaarup/aula/files/10579372/home-assistant_aula_2023-02-03T13-28-12.536Z.log)

sensor. og calendar.skoleskema.* ser ud til at virke i denne version, men binary_sensor.aula_aulamessage fejler.

Jeg håber at du kan bruge den vedhæftede debug log, jeg har strippet den for andet data end AULA relateret.

/ Johnny

**Comment by scaarup** [comment]
Tak @SkinnyGnome.

Vil du prøve at hive seneste ændring på branchen og teste igen? Du har ikke debug logging slået til, det må du gerne, så vi forhåbentlig kan se lidt mere.

Tak.

**Comment by SkinnyGnome** [comment]
Hej,
Jeg troede at det var nok at markere 'Debug' på integrationen, men det var det ikke :-)
Jeg har installeret seneste update og aktiveret debug for custom_components.aula.

Fejlen for custom_components.aula.binary_sensor er forsvundet, med selve sensoren ser ikke ud til at blive opdateret med data.

Jeg har vedhæftet log ( Jeg har fjernet navne og så videre fra den, så kun linjer for Aula integrationen er med.

[home-assistant_aula_2023-02-06T11-15-50.270Z.log](https://github.com/scaarup/aula/files/10662564/home-assistant_aula_2023-02-06T11-15-50.270Z.log)


Jeg håber at det kan bruges.

**Comment by scaarup** [comment]
Hej.
Det med at markere til debug i UI'et må jeg få lavet en anden gang, tror det er noget integrationen skal understøtte :).

Vil du lige opdatere og prøve igen. Jeg tror jeg fandt fejlen.

**Comment by SkinnyGnome** [comment]
Hej,

Så har jeg testet seneste version.
Binary_sensor virker igen og den indeholder også tekst fra seneste besked.

**Comment by scaarup** [comment]
Super - tak 👌🏻
