### ISSUE TITLE
After newest update - error setting up

### ISSUE THREAD

**Issue by Symbiot78** [scaarup/aula#93]
**Please answer the following**
- Version of integration: 
- Version of Home Assistant: 2023.4.1
- [ x] I have more than one child

this is what it shows in the debug log..

[homeassistant.config_entries] Error importing platform config_flow from integration aula to set up aula configuration entry: No module named 'custom_components.aula.config_flow'

**Comment by Symbiot78** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:363
First occurred: 10:19:16 (1 occurrences)
Last logged: 10:19:16

Error importing platform config_flow from integration aula to set up aula configuration entry: No module named 'custom_components.aula.config_flow'

**Comment by scaarup** [comment]
Hi.
I have just updated to 2023.4.1 and I am not seeing any errors. 
You have to add debug log for me to investigate. One single line with an error is not enough.

**Comment by Symbiot78** [comment]
hi..
enabled debug from UI.. then redownloaded aula integration & rebooted HA.
now.. no error.
God knows what it was complaining about.
