### ISSUE TITLE
Aula Integration is not loaded after Aula update

### ISSUE THREAD

**Issue by SkinnyGnome** [scaarup/aula#96]
**Describe the bug or problem (In Danish is OK)**
After the Aula update this weekend, the integration stopped updating sensors.
ll the sensors became unavailable.

I have tried the following without success:
* 1
> Removed the integration.
> Created new Unilogin Password.
> Readded the integration with new password.

* 2
> Removed the integration
> Reinstalled the Aula Integration in HACS
> Added the integration.

**Please answer the following**
- Version of integration: v0.1.31
- Version of Home Assistant:
> - Home Assistant 2023.4.6
> - Supervisor 2023.04.1
> - Operating System 10.0

- [*] I have more than one child
- [*] My children are attending different schools / institutions

**Please provide debug log from the integration**
- Enable by adding the following to your configuration.yaml:
```
logger:
  default: info
  logs:
    custom_components.aula: debug
```
- Restart Home Assistant
- Capture all log lines (from the integration only), save it to a file and attach it to here.
[Aula_Debug.txt](https://github.com/scaarup/aula/files/11319512/Aula_Debug.txt)

**Comment by scaarup** [comment]
Caused by this: https://viden.stil.dk/pages/viewpage.action?pageId=185468332

**Comment by PTST** [comment]
v0.1.32 has fixed this issue for me as well

**Comment by scaarup** [comment]
Awesome.

**Comment by scaarup** [comment]
Thanks for reporting :)
