### ISSUE TITLE
Får ikke længere nogle info

### ISSUE THREAD

**Issue by ghozt1989** [scaarup/aula#99]
Jeg ved ikke om det kun er hos mig der ikke længere kommer info ind. Jeg har kopiret fejl koden fra Home assistent ind her. Ved ikke om der evt er flere info du skal bruge eller?

Home Assistant Core
Error while setting up aula platform for sensor
08.34.33 – (FEJL) Sensor (brugerdefineret integration) - beskeden forekom først kl. 08.01.03 og ses 5 gange
Unexpected error fetching sensor data: 'NoneType' object is not subscriptable
08.34.33 – (FEJL) Aula (brugerdefineret integration) - beskeden forekom først kl. 08.01.01 og ses 5 gange

**Comment by ghozt1989** [comment]
Jeg havde selfvføldig ikke lige prøve at slette aula og lægge det ind igen. Nu virker det igen jeg lukker den igen beklager hvis jeg nåede at ulejlige dig :)

**Comment by scaarup** [comment]
Hej @ghozt1989 .
Jeg nåede ikke at kigge på noget, men det var godt du fik det løst :)
